name: Validate

on:
  push:
    paths-ignore: 
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate
    runs-on: macos-13
    if: github.repository_owner == 'permatag'
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        run: |
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install -r requirements.txt
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install packaging
          rm -rf Univ*
          aria2c -x 16 https://github.com/dortania/PatcherSupportPkg/releases/download/1.9.5/Universal-Binaries.dmg
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 OCLP-Mod-GUI.command --validate
    
